export const FETCH_WINE_SUCCESS = 'FETCH_WINE_SUCCESS';

export const SET_FILTER = 'SET_FILTER';
export const SET_QUERY = 'SET_QUERY';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';

export const CHANGE_COUNT_PAGES = 'CHANGE_COUNT_PAGES';